// Copyright (C) 2016 Kim Bilida All rights reserved.

using System;
using System.ServiceModel;
using GildedRose.ServiceLibrary.Model;
using System.ServiceModel.Web;

namespace GildedRose.ServiceLibrary
{
   /// <summary>
   ///    Provides methods to access the GildedRose services
   /// </summary>
   [ServiceContract(Namespace = Constants.ServiceNamespace)]
   public interface IGildedRoseService
   {
      /// <summary>
      ///    Retrieves the entire inventory.
      /// </summary>
      /// <returns></returns>
      /// <remarks>As inventory increases new methods to provide searching and paging will be introduced.</remarks>
      [OperationContract]
      [WebGet( BodyStyle = WebMessageBodyStyle.WrappedRequest)]
      ItemsRequestResponse GetAllItems();

      /// <summary>
      ///    Buys the item.
      /// </summary>
      /// <param name="token">The token generated by <see cref="RequestToken" />.</param>
      /// <param name="itemId">The Guid of the item.</param>
      /// <param name="quantity">The quantity.</param>
      /// <returns></returns>
      [OperationContract]
      [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest)]
      RequestResponse BuyItem(string token, Guid itemId, int quantity);

      /// <summary>
      ///    Authenticates the user and provides a token for use in other calls.
      /// </summary>
      /// <param name="name">The name.</param>
      /// <param name="password">The password.</param>
      /// <returns></returns>
      [OperationContract]
      [WebGet(UriTemplate= "RequestToken?name={name}&password={password}", ResponseFormat=WebMessageFormat.Xml,BodyStyle = WebMessageBodyStyle.WrappedRequest)]
      TokenRequestResponse RequestToken(string name, string password);
   }
}